name: Laravel

on: pull_request

jobs:
  laravel-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'SKIP ACTIONS')"
    container: owow/laravel-php:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: laravel_testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --tmpfs="/var/lib/mysql"

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Composer
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer config "github-oauth.github.com" "${{ secrets.COMPOSER_AUTH }}"
          composer install --no-scripts

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Yarn
        run: |
          yarn
          yarn production

      - name: Code sniffer
        run: |
          vendor/bin/pint --test

      - name: Prepare
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan jwt:secret --force

      - name: Unit - Phpunit
        env:
          DB_HOST: mysql
        run: |
          vendor/bin/phpunit tests/Unit

      - name: Feature - Phpunit
        env:
          DB_HOST: mysql
        run: |
          vendor/bin/phpunit tests/Feature
